### ISSUE TITLE
both experiment/regs.sh and full.sh should be registering with correct entitlement setup and allow for simple variant

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#138]
First variant (name it something like "With Auto-Attach"): setup the activation key to have allocated subscriptions for RHEL + SatTools

Second variant (a.k.a. "Simple Content Access"): setup the activation key to not have any allocated subscriptions (so <AK> -> Subscriptions -> List/Remove is empty) but have RHEL + SatTools repositories set to 'Enabled (overriden)' - e.g.: https://i.imgur.com/BKa1hDH.png

We should be measuring both variants.

**Comment by jhutar** [comment]
Discussed in `Subject: Re: [Results] Satellite 6.7 Scale Tests` email thread

**Comment by Imaanpreet** [comment]
Migrated to jira - https://issues.redhat.com/browse/SAT-6378
