### ISSUE TITLE
Add complex CV publish test

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#145]
Get everything frozen at <date> for RHEL8 appstream+baseos+supplementary+satTools"

CV settings:

"Solve Dependencies = Yes"
- exclude_puppet: RPM exclude (puppet, puppet-agent)
- include_base: RPM, include (Include all RPMs with no errata)
- include_modules: Module Streams, include (Include all Module Streams with no errata)
- include_errata: Errata - Date and Type, include (affected repos: All, updated on, End date 2020-10-01)

**Comment by Imaanpreet** [comment]
Migrated to jira - https://issues.redhat.com/browse/SAT-6377
