### ISSUE TITLE
Redesign satperf with locust 

### ISSUE THREAD

**Issue by psuriset** [redhat-performance/satperf#146]
Ref: pulp3 results

**Comment by jhutar** [comment]
Hello @psuriset . Was this meant for this other repo? https://github.com/redhat-performance/pulpperf/

**Comment by psuriset** [comment]
Yes for pulpperf. But do you see a need for satellite too?  Probably concurrent registrations?

**Comment by jhutar** [comment]
Yeah, might be doable, but QE have a tool to register these "dead" profiles already. We are mostly registering "live" hosts (containers that acts as real hosts for this purpose).

**Comment by jhutar** [comment]
Created https://github.com/redhat-performance/pulpperf/issues/4
