### ISSUE TITLE
Create pulp read test case

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#149]
Basically we want to download as many packages by many hosts in parallel

**Comment by IshanSinghal** [comment]
By running yumdownloader .. via ReX (SSH), we measure download speed from Satellite to registered clients. Results for sat 6.9 and sat 6.10 - [1](https://docs.google.com/document/d/1NlCnAzG884rejbBbxC55P8JTQC7KEL6pYulXDk3i2fo/edit#heading=h.lziv3640jlmw) and [2](https://docs.google.com/spreadsheets/d/1n6lqjo28fwa5GacHHg2UAyy1typRQVoZdIGah9hjXNc/edit#gid=49454227)
