### ISSUE TITLE
Get Sat logs to ElasticSearch

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#151]
Part of this is also ensuring index is automatically rolled up after some time or size.

**Comment by jhutar** [comment]
List of indexes we are using: https://docs.google.com/document/d/1aAwSIO1KiuwwbnLcXNSks90b2zluL_mp9tS-u8NT1K8

**Comment by Imaanpreet** [comment]
Migrated to jira - https://issues.redhat.com/browse/SAT-6373
