### ISSUE TITLE
Ensure whole worklow works fine with capsules

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#152]
⏰ Investigate: #67 
⏰ Investigate: #66 
⏰ Ensure full pipeline is working
✅ Ensure capsules are used for ReX
⏰ Register N hosts via capsule - find breaking point and find tunings to go beyond that:
    - 1.5k (60 containers concurrently)
    - (p3) 2k <- old
    - (p3) 3k
    - (p3) 4k
    - 5k
    - (p2) 10k
    - (p2) use containers with more packages
    - capture:
        - average reg time and compare with avg reg time on Sat
        - sys load and sys mem
⏰ Run regs.sh - find breaking point and find tunings to go beyond that
⏰ Run ReX on N hosts - find breaking point and find tunings to go beyond that
    - more workloads:
        - date
        - yum install package
        - command that update package profile
⏰ Sync N repos to capsule - find breaking point and find tunings to go beyond that
⏰ Add scaling suggestions (t-shirt sizes) to the tuning guide
⏰ Add tuning suggestions to the tuning guide

**Comment by jhutar** [comment]
No need to test all of above ^^^ @IshanSinghal

**Comment by Imaanpreet** [comment]
Migrated to jira - https://issues.redhat.com/browse/SAT-6372

Thank you!
