### ISSUE TITLE
Test to measure hosts creation

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#163]
I.e. not registration, but creating the host as you would do before host provisioning - second part of below citation from lzap (slightly modified).

> 1) Performance of hosts which are downloading files and configuration
> from PXE, accessing DHCP, and downloading stage2 init ramdisk and RPM
> packages from Capsule. This is usually not a huge issue as Satellite
> can be easily scaled out - more PXE/DHCP/Content Capsules can be
> deployed to cover the load. It is good to know some numbers to know
> how many clients can a Capsule serve.
> 
> 2) Performance of hosts creation - this is probably a more fragile
> aspect. When a host is created with provisioning configuration, many
> steps need to be done: PXE files deployed, kernel/image downloaded,
> free IP address acquired and tested, DHCP reservation created. When
> this is done concurrently, Satellite can choke. This is the
> more important aspect from engineering POV. This can be mocked
> easily - it can be done just via hammer for example.

**Comment by jhutar** [comment]
Hello @lzap, please do you happen to have some script to setup clean Satellite so hosts can be then created via hammer? Provisioning itself would not be attempted after that, we would just try host creation in parallel I think.

**Comment by lzap** [comment]
Cheers Jan! So you want a script that installs Satellite? I do have but its quite complex, all you need to do is to install regular satellite with TFTP and DHCP enabled, create a domain, a subnet, an os, associate templates, create a hostgroup and then you can start creating hosts. Check if DHCP and TFTP is orchestrated (dhcpd.leases + /var/lib/tftproot/boot).

**Comment by jhutar** [comment]
Hello :) We have scripts to install Sat, I was just hoping for a script that would "create a domain, a subnet, an os, associate templates, create a hostgroup and then you can start creating hosts" :) I remember you had something - set of shell (?) scripts with all the needed commands like `01-install-satellite.sh`, `02-create-domain.sh`... Just wanted something to copy&paste from. Please ignore me if I confused it somehow.

**Comment by lzap** [comment]
Yeah something is here: https://gitlab.sat.engineering.redhat.com/lzapleta/provisioning-setup

**Comment by lzap** [comment]
Sent via email.

**Comment by Imaanpreet** [comment]
Migrated to jira - https://issues.redhat.com/browse/SAT-6371

Thank you!
