### ISSUE TITLE
Remove all hosts  to clean up

### ISSUE THREAD

**Issue by psuriset** [redhat-performance/satperf#26]
Playbooks to clean up hosts & queues ..etc to start registrations again.

**Comment by jhutar** [comment]
IMO this was meant here: https://github.com/redhat-performance/satperf/blob/master/playbooks/satellite/satellite-remove-hosts.yaml

Might be  agood idea to have a playbook/role to cleanup tasks from Sat - maybe this could work: https://access.redhat.com/solutions/2755731

Another useful cleanup step could be to vacuum postgreSQL: https://www.postgresql.org/docs/9.5/static/sql-vacuum.html

And MongoDB repair: https://access.redhat.com/solutions/3052771 or https://access.redhat.com/solutions/3161321 (not sure if/how do these differ)

**Comment by jhutar** [comment]
IMO this was resolved

**Comment by ritwik12** [comment]
@jhutar Been 2 years 😅
