### ISSUE TITLE
only restart network when something changed there (in that role)

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#40]
https://github.com/redhat-performance/satellite-performance/blob/master/playbooks/satellite/roles/scalelab-nic-cleanup/tasks/main.yaml#L36-L43

IMO we can use handlers nicely for this:

http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change

**Comment by Imaanpreet** [comment]
@jhutar Hello, do we need to migrate this issue to Jira?

**Comment by jhutar** [comment]
@Imaanpreet Yes please

**Comment by Imaanpreet** [comment]
Migrated to jira - https://issues.redhat.com/browse/SAT-6380
