### ISSUE TITLE
is subscription-manage works inside container?

### ISSUE THREAD

**Issue by dhajoshi** [redhat-performance/satperf#54]
when i try to run subscription-manager inside container it gives me message that you cannot run subscrption-manager inside container.

**Comment by psuriset** [comment]
Can you share use case here? 
I dont think, you need to register containers unless you are exploring performance/scale. 

This might help you. 
https://github.com/redhat-performance/satellite-performance/blob/master/playbooks/satellite/roles/client-scripts/files/clients.yaml.j2

**Comment by dhajoshi** [comment]
yes, i am trying to register some containers to my satellite and trying to observe performance of syncing, puppet agent, install/uninstall packages and so on.

**Comment by jhutar** [comment]
Please make sure you do this in the container before registering it:

https://github.com/redhat-performance/satellite-performance/blob/master/playbooks/satellite/roles/client-scripts/files/clients.yaml.j2#L83-L86
