### ISSUE TITLE
Admin -> Settings -> RemoteExecution -> remote_execution_connect_by_ip needs to be configured to true

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#61]

**Comment by h4xr** [comment]
@sourabhtk37 Can you please pick this up :)

**Comment by sourabhtk37** [comment]
Is this required specific cases or in general(eg: DNS is not resolving) @jhutar ?

**Comment by h4xr** [comment]
@sourabhtk37 It is basically a drawback of how our infrastructure gives hostnames to containers. We cannot connect to them using the hostname resolution and require a direct connection by IP.
