### ISSUE TITLE
make sure docker0 bridge on atomic host have private net interface assigned

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#64]
I have successfully used this:

    nmcli connection add type bridge-slave ifname p1p1 master docker0
    nmcli connection mod docker0 ipv4.address "{{ ip }}/8"
    nmcli connection down docker0
    nmcli connection up docker0   # FIXME: this failed, but docker0 seems OK, investigation needed

**Comment by h4xr** [comment]
Closing this issue, since we are not working on Atomic host anymore
