### ISSUE TITLE
Do we need both base_capsule_pool and sat_capsule_pool?

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satperf#66]
Need to check git blame before desicion

**Comment by kbidarkar** [comment]
This was changed by me, as not all manifests would have `Employee SKU` and so this was added in, https://github.com/redhat-performance/satellite-performance/pull/62#issue-263390685

If you have other ideas, we can discuss and update accordingly. :) 

The manifests which I used did not have, `Employee SKU` and so...

**Comment by kbidarkar** [comment]
More precise info here, https://github.com/redhat-performance/satellite-performance/pull/62#issuecomment-334719849

**Comment by Imaanpreet** [comment]
We are thinking/plaining to simply the entire Satellite Perf repo and will be keep posting the details in README section. 
You can reopen the issue if you want the updates here. Thank you.
