### ISSUE TITLE
Switch from screen to open

### ISSUE THREAD

**Issue by h4xr** [redhat-performance/satperf#68]
Opening this issue so as to initiate a discussion

Currently we use screen to run our commands as a background process so even if a user has issues with their network connectivity, the command can still run.

The same kind of functionality is provided by the open command which comes pre-installed with the distribution.

The general syntax for launching the command in the background is

open [command]

So, I will like to put forward the proposal of dropping screen and using open instead.

@jhutar

**Comment by jhutar** [comment]
We are now using mostly CI to run our playbooks.

And yes, sorry for this 2+ year lag :)

Greetings and happy new year if you are reading this! :)
