### ISSUE TITLE
Capsule Installation is Broken

### ISSUE THREAD

**Issue by h4xr** [redhat-performance/satperf#80]
Capsule setup playbooks point to roles which don't exist

**Comment by jhutar** [comment]
Maybe for @rdrazny ?

**Comment by ritwik12** [comment]
I guess the roles mentioned are 

> satperf/playbooks/common/roles/

 not 

> satperf/playbooks/satellite/roles/

Let me know if you are pointing something else @h4xr

**Comment by h4xr** [comment]
This has been fixed with #4d5722178f70e0b37e90a9d099ce20da6c60e106

**Comment by h4xr** [comment]
Already fixed.

@ritwik12 The path to the roles was incorrect, we were trying to reference common roles from inside of satellite folder even after moving them to their own separate directory
