### ISSUE TITLE
Bug with attaching pool

### ISSUE THREAD

**Issue by ritwik12** [redhat-performance/satperf#84]
Even after dealing with null value of "querying" in #83,  the pool is not able to attach. I guess there is some bug with it.

**Comment by h4xr** [comment]
@ritwik12 The bug apparently happens due to the use of redhat_subscription module in Ansible not able to deal with the multiple Pool IDs for the same pool, hence leaving the pool attach phase incomplete.

**Comment by ritwik12** [comment]
Yeah, I think #67 states the same issue.

**Comment by h4xr** [comment]
@ritwik12 #67 tracks a different issue, which causes duplication of options, but in the current we are supposed to have them there due to susbscription dependency.

**Comment by jhutar** [comment]
Stale for too long
