### ISSUE TITLE
Validate existence of supplied ssh keys

### ISSUE THREAD

**Issue by sourabhtk37** [redhat-performance/satperf#97]
While installing satellite using `$ ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/satellite/installation.yaml --skip-tags "non-async"`. Right now there are no steps to ensure the ssh keys supplied exists or not.

**Comment by jhutar** [comment]
Sorry, I do not understand the problem. Could you please show the error you are facing or explain what was the issue? Thank you!

**Comment by sourabhtk37** [comment]
I tried to run ansible playbooks without providing the private key in the path specified(`conf/`). Playbook went on to run, threw error when it wasn't able to establish ssh connection.

**Comment by h4xr** [comment]
@sourabhtk37 @jhutar This seems more of an issue with ansible-playbook command and not satperf in itself.
Will be a better candidate for raising an issue around ansible-playbook command

**Comment by sourabhtk37** [comment]
Yeah, Agreed. Closing this.
